#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
# Note that you can also use a custom carpentry type. For more info,
# see the documentation: https://carpentries.github.io/sandpaper-docs/editing.html
carpentry: 'rcac'
varnish: aseetharam/varnish
#carpentry_description: "Custom Carpentry"

# Overall title for pages.
title: 'Genome Assembly: Hands-on Training'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: '2025-02-05'

# Comma-separated list of keywords for the lesson
keywords: 'gene-assembly, pacbio, oxford-nanopore, hifasm, flye, medaka, busco, quast'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'stable'

# License of the lesson materials (recommended CC-BY 4.0)
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://example.com/FIXME-template-source'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'rcac-help@purdue.edu'

episodes:
- introduction.Rmd
- assembly-strategies.Rmd
- data-quality-control.Rmd
- pacbio-hifi-assembly.Rmd
- oxford-nanopore-assembly.Rmd
- hybrid-assembly.Rmd
- scaffolding-using-ogm.Rmd
- assembly-evaluation.Rmd
- assembly-visualization.Rmd


#
learners:
 - setup.md
#
instructors:
- instructor-notes.md
#
profiles:
- learner-profiles.md


disable_sidebar_numbering: true